### ISSUE TITLE
Bug TNDBS.TaleNewsPawnDied 

### ISSUE THREAD

**Issue by Mihokyo** [Vectorial1024/Desynchronized#8] opened 2019-04-27 13:09 UTC
https://dpaste.de/qsfe

I will try to look in source, but I'm not sure to understanding !

**Comment by Vectorial1024** [comment] 2019-04-27 13:25
This is a known issue on Steam, but I forgot to add an entry here. Thanks for the help!

I have already found a solution to this problem. The fix will come out in the next update.

**Comment by Vectorial1024** [comment] 2019-04-27 15:59
The issue is not over yet, since I am still testing my solution.

**Comment by Vectorial1024** [comment] 2019-04-27 16:29
Fix is confirmed to be working fine. Closing for real.

**Closed as completed by Vectorial1024** 2019-04-27 16:29 UTC
Labels: bug, completed

**Comment by Vectorial1024** [comment] 2019-05-08 07:54
The bug is fixed in the latest release (v1.5.0).
